name: Continuous Builder
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'metadata/**'
      - 'legal/**'
      - '**.md'
      - '**.csv'
      - '**.py'
      - 'app/src/release/generated/baselineProfiles/**-prof.txt'
      - 'app/**.pro'
      - 'LICENSE'
      - '.github/workflows/release-builder.yml'
      - '.github/workflows/fossa.yml'
      - '.github/workflows/update-device-catalog.yml'
      - '.github/FUNDING.yml'
      - '.editorconfig'
      - '.idea/**'
  pull_request:

jobs:
  build:
    name: Continuous Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: burrunan/gradle-cache-action@v1
        name: Build APK with cached .gradle
        with:
          job-id: assembleRelease
          # Makes all non-main branch builds to use read-only caching
          read-only: ${{ github.ref != 'refs/heads/main' }}
          # Arguments for Gradle execution
          arguments: assembleRelease --stacktrace
          # Extra files to take into account for ~/.gradle/caches dependencies
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml

      - name: List build output
        run: |
          cd app/build/outputs/apk/release/
          ls
