name: FOSSA license scan
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.gitignore'
      - 'metadata/**'
      - 'legal/**'
      - '**.md'
      - '**.csv'
      - '**.py'
      - 'app/src/main/baseline-prof.txt'
      - '.github/workflows/**'
      - '.github/FUNDING.yml'
  
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
          
      - name: Setup JDK
        uses: actions/setup-java@v4
        with: 
          distribution: 'zulu'
          java-version: '17'
        
      - name: Install FOSSA CLI
        run: "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | sudo bash"
        
      - name: Run FOSSA scan
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: fossa analyze
